import React from 'react'
import HeaderBlog from '../../components/HeaderBlog'
import HeaderBlogPost from '../../components/HeaderBlogPost'
import MiniMainViewBlog from '../../components/MiniMainViewBlog'


export default function Okupados() {

  const temat = "Co z Okupados, Okupas, Okupado?... wie Pan o co chodzi"

  return (
    <>
    <HeaderBlogPost temat={temat}/>
<div className='lg:px-40 px-4 pt-24'>

No właśnie to pytanie zyskało od początku 2022 roku ogromną (nie)sławę. Niezwykle wrażliwy i wzbudzający wiele kontrowersji temat. Ze względu na to, że leży on u fundamentów jakichkolwiek inwestycji w Hiszpanii, a Polskie media nie dostarczają zbyt wielu sensownych informacji. Przeszukaliśmy zatem Hiszpańskie media traktujące o problemie na poziomie prawnym oraz konkretnych przypadków z życia wziętych aby nadać temu nieco rzeczywistego wymiaru.<br></br><br></br>
<b>\"Czym są okupas, okupados, ocupatos?... Wie Pan o chodzi.\"</b> <br></br><br></br>Jakkolwiek by tego określenia nie przekręcić – każdy raczej wie o co chodzi. Okupados jest nazywany „ruchem” lub „społeczną inicjatywą”. Związana jest z nim cała ideologia, która ma być oparta o prawa człowieka do np. dachu nad głową, swojego miejsca. Nie zmienia to faktu iż drugą stroną medalu (tą stroną osób kupujących nieruchomość w Hiszpanii) owego dość nieścisłego prawa jest zagrożenie zwyczajnego i (zdawać by się mogło) bezprawnego przejęcia mieszkania, domu przez „zasiedzianą osobę” - okupados. Zatem czy człowiek, który wszedł do mojego domu naprawdę może stać się Jego właścicielem? I tak i nie. Brzmi wystarczająco kuriozalnie?  Rozpracujmy to zagadnienie.<br></br><br></br>
<b>Okupas, okupados, ocupatos, jednak najczęściej „Okupa”.</b><br></br><br></br>

Choć będziemy używać różnych nazw w tym arykule - dlaczego Okupa? Aby nie generować negatywnych konotacji kojarzonych z „bezprawnym okupowaniem” i uniknąć społeczno-prawnych kontrowersji w ramach tego tematu oraz nie narażać się na oskrżenia o swojego rodzaju napiętnowanie. „Jakie napiętnowanie” - zapewne pomyślała część z Was Drodzy Czytelnicy. Otóż sprawa nie jest taka prosta...<br></br><br></br>

Jak wspomniałem wyżej okupados to jedyna w swoim rodzaju społeczność lub ruch społeczny, który nie tylko w Hiszpanii znalazł swoją przestrzeń i odpowiedni grunt ale również w wielu innych krajach europejskich. Niestety to w Hiszpanii od 1984r. najbardziej wrósł się w kulturę powodując dziś sporo kontrowersji, bo czasy się jednak nieco zmieniły. Zatem kiedy to było zasadne? Okres kiedy w Hiszpanii stało pustych wiele nieużytków a ludzie, ba, całe rodziny nie miały się gdzie podziać ponieważ nie było ich stać na czynsz - w ramach własnego ratunku zajmowały stare, często zniszczone lokale mieszkalne. Lokale pozornie ale i praktycznie nienależące do nikogo. Ruch zatem zrodził się z chęci przetrwania, a nie łatwego wzbogacenia się lub przestępczego pomysłu na kradzież mieszkań. Zatem intencją oraz głównym argumentem było zwyczajnie konstruktywne wykorzystanie opuszczonych przestrzeni, zrobienie z Nich użytku. Dlatego prawo zaczęło to wspierać.<br></br><br></br>

Zatem mówiąć wprost - Hiszpańskie prawo robi z osoby która weszła do domu prawowitego właściciela. Pod jednym warunkiem. Lokator musi się tam znajdować min. 48 godzin. Jeśli prawowity właściciel nie umie udowodnić, że było inaczej – mieszkanie „zyskuje” nowego właściciela - okupados. Jeśli jednak potrafi udowodnić – Hiszpańska Policja siłą i bez nakazu w trybie natychmiastowych pozbywa się bezprawnych lokatora lub lokatorów. Jeśli natomiast właściciel zareguaje po owych magicznych wręcz 48 godzinach - sprawa wymaga wprowadzenia  na drogę sądową.<br></br><br></br>

Należy Pamiętać, że Hiszpańskie  prawo w postaci artykułu 202 chroni ofiary włamań i mówi, że osoba, która siłą wtargnęła na nie swoją posesję dopuściła się aktywności kryminalnej za co grozi do 6 lat więzienia. Zatem jest to silne zabezpieczenie przed włamaniami do domów, które mają systemy monitoringu, akty notarialne lub dowody własnościm ponieważ akt włamania jest do udowodnienia bardzo szybko. np. włączeniem alarmu, nagraniem wejścia „lokatora” na kamerach, rejestracją wejść do lokalu. Trzeba jednak pamiętać, że liczy się czas reakcji i te 48 h jest kluczowe aby sprawa została rozwiązana w miarę szybko i bezpoleśnie.<br></br><br></br>

Na tle tego można domniemać, że problem dotyczy biedniejszych dzielnic Hiszpanii o słabych zabezpieczeniach lub braku zabezpieczeń obiektów i tam gdzie trudno udowodnić własność bo dokumenty przepadły lub są gdzieś zapodziane lub jest tania nieruchomość z rynku wtórnego, która nie ma żadnej z tych rzeczy.<br></br><br></br>

Hiszpanie są na ogół zgodni, że przydałyby się skuteczniejsze środki, które szybciej mogą rozwiązać problem niechcianego lokatora - choć dotyczy on (problem okupatos) niewielkiej , wręcz marginalej części Hiszpanii i raczej nieużytków, pustostanów lub mieszkań z przejęć bankowych, które latami stoją puste to mimo wszystko wspomniane wyżej „ nieścisłości” powodują nadużycia i są sytuacje przejęć (na tle przestępczym) lokali lub całych kamienic siłą przez ugrupowania aby w następnej kolejności „wynajmować” owe lokale. Mimo tego że skala tego problemu jest jw. marginalna to aktywność przestępcza oparta o to prawo słusznie powoduje ogromną falę sprzeciwu społecznego, o którym w efekcie głośno w mediach i który powduje sporo nieporozumień i lęku. Niemniej bez względu na to czy włamanie miało miejsce w obiekcie gdzie właściciel poświadczył własność lub nie miał takiego dokumentu  Hiszpanie mają ok 93% skuteczność w odzyskiwaniu mieszkań.<br></br><br></br>

<b>Wzrost ruchu okupados.</b><br></br><br></br>

W czasie pandemii niestety ta „zła” forma okupowania mieszkań wzrosła na sile. Nie chodzi tutaj o włamania do lokali pod wynajem krótko terminowy lecz ludzie, którzy stracili pracę, skończyły im się pieniądze wraz z rodzinami posunęli się do „zasiedzenia”. Kryzys światowy i nieszczelny system prawny w Państwie nie wytrzymał w zderzeniu ludzką tragedią. Ilość zasiedzeń wzrosła niemniej dalej stanowi wartość marginalną np. w Barcelonie jest to ok. 0.006 % mieszkańców co nie zmienia faktu iż jest duża grupa, która ludzi często kierowana instynktem przetrwania złamała prawo.<br></br><br></br>

są to sytaucja na wzór - wprowadzająca się do wynajmowanego mieszkania para przestaje płacić za czynsz i zostaje na dłużej dopóki właściciel podstępem nie zmieni zamków podczas wakacji owych okupados. O takcich sytuacjach było chyba najgłośniej w mediach.<br></br><br></br>

<b>Możliwe rozwiązania.</b><br></br><br></br>

1. Najlepszym rozwiązaniem jest po prostu dobre zabezpieczenie i szybka reakcja. Mimo tego, że problem okupados na tle mieszkań inwestycyjnych stanowi raczej wyjątkową rzadkość (my oraz nasi partnerzy nie odnotowaliśmy włamania od ok 7 lat, a problem okupados nie dotknął nigdy).Można zabiezpieczyć się współpracą z firmą ochroniarską, która ma za zadanie zareagować w przypadku włączenia alarmu (nieautoryzowane wejście), systemu video-monitoringu, są systemy, które w czasie rzeczywistym uruchamiają aplikację w telefonie o nieautoryzowanym wejściu. Czasu na zgłoszenie problemu jest wtedy sporo bo 48 godzin. Zatem przesłanie nagrania z monitoringu na Policję w tym oknie czasowym powoduje natychmiastowe „wyproszenie” przez Policję gości i utratę statusu „ocupados”. Jakkolwiek to brzmi. Warto aby akt własności nie znajdywał się w miejscu potencjalnego włamania ponieważ „po fakcie” nie będzie możliwe wejście do domu aby go przedstawić bo będzie owy dom okupowany bez mozliwości wejścia prawdopodbnie.<br></br>
2. Jeśli nie uda nam się zareagować w ciągu owych 48 godzin, a mamy dostępny akt własności możemy wystosować prawne pismo bezpośredno do okupados o natychmiastowe opuszczenie lokalu załączając dokument potwierdzający własność. Nie jest konieczne pisemne potwierdzenie ich tożsamości co jest uproszczeniem. Taki Okupados ma 5 dni  na udowodnienie, że jest inaczej, jeśli tego nie zrobi sąd wydaje natychmiastowy nakaz eksmisji bez możliwości odwołania się okupados od tej decyzji. Pamiętajmy o artykule 202  i karze pozbawienia wolności do 6 lat takiego delikwenta.<br></br>
3. Jeśli minie 48 h i nie mamy dostępu aktu własności to mamy większy problem, ponieważ proces wchodzi na drogę sądową, która zapewne skończy się udowodnienem własności prędzej czy później, natomiast w tym przypadku może to potrwać nawet ponad rok. Hiszpańskie sądy od niedawna zaczęły traktować sprawy tego rodzaju jako priorytetowe co nie zmienia faktu, że trzeba się liczyć z kilkoma/kilkunastoma miesiącami.<br></br>
4. Jeśli minęło 48 godzin, ostatnią z (niepolecanych) opcji jest „na własną rękę”, czyli użycie dość silnych argumentów perswazji samemu lub z pomocą lokalnych firm niemniej taki ruch może być karalny. Prawo Hiszpańskie może uznać to za próbę pozbycia się obecnego właściciela domu siłą i bez podstaw prawnych. Jedną z takich nieoficjalnych metod jest wymiana zamków podczas min 48 h nieobecności okupados. Opcji tej nie polecamy.<br></br><br></br>
<b>Podsumowując. </b><br></br><br></br>Prawo do wejścia do obiektu i zawłaszczenia go jest mocno przeterminowane i nie zostało dopasowane do obecnych czasów, rodzi patologie i może wspierać działania przestępcze w mocno nieunormowanych i niezaopiekowanych dzielnicach. Pamiętajmy jednak, że taki Okupados w przypadku nawet podejrzenia zabezpieczeń tj. alarmu, monitoring w upatrzonym raczej przestaje się nim interesować ponieważ na szali stawia 6 lat więzienia za włamanie, które raczej na 99% zostanie udowodnione. Dlatego ta „przestępcza wersja” okupados  dotyczy głównie środkowych i części Hiszpanii jak np. blokowiska, których niestety nie brakuje. <br></br><br></br>Nie wyklucza to jednak faktu iż mogą znaleźć się hakerzy,m odważni lubi Ci którzy granicę odwagu już przekroczyli oraz nie do końca świadomi, którzy niedoczytali prawa - którzy mogą spróbować włamania do domu z monitoringem i alarmem bo nie wiedzieli, że trzeba przesiedzieć 48 h i bronić się jak w Hiszpańskim La Casa de Papel (Hiszpański serial Dom z Papieru).<br></br><br></br>  aby zdobyć nowy teren.

W związku z powyższym, nie ma powodów do paniki, jednak zabezpieczajmy się na zasadzie podobnej jak zrobilibyśmy to w naszych domach w Polsce. Te same metody powinny rozwiązać różne zagrożenia w tym Hiszpańskich Ocupados.<br></br><br></br> <br></br><br></br> 
    </div>
    </>
  )
}
